---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
   - name: Copy WAR file to Tomcat
     copy:
       src: "target/2023MavenWebAppPipelineWithAnsible.war"
       dest: "/opt/tomcat/webapps/"
       remote_src: no
       
   - name: Restart Tomcat
     systemd:
        name: tomcat
        state: restarted   
